# vim: set fdm=marker :
#
# @author: Viktor Alex Brynjarsson
#
# My .zshrc
#             now with added oh-my-zsh
#

# {{{ oh-my-zsh
ZSH=$HOME/.oh-my-zsh
plugins=(git django fabric pip yum vi-mode colored-man)

source $ZSH/oh-my-zsh.sh
# }}}

# {{{ modules, options and settings
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=$HISTSIZE
PATH=$PATH:~/bin:/opt/local/bin:/sbin/
PAGER=less

# echo $(( sin(1/4.0)**2 + cos(1/4.0)**2 - 1 ))
zmodload zsh/mathfunc

setopt APPEND_HISTORY
setopt NOTIFY
setopt AUTO_MENU
setopt REC_EXACT
setopt EXTENDED_GLOB
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

unsetopt BEEP
unsetopt NO_MATCH
# }}}

# {{{ key bindings
# use a vim style input
bindkey -v

# search backwards and forwards using default vim keys (in normal mode)
bindkey -M vicmd '/' history-incremental-search-backward
bindkey -M vicmd '?' history-incremental-search-forward
# if I'm not in normal mode Ctrl+r or Ctrl+s will search backwards and
# forwards respectively
bindkey -M viins '^R' history-incremental-search-backward
bindkey -M viins '^S' history-incremental-search-forward

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
# }}}

# {{{ prompt

# vi mode indicator
MODE_INDICATOR="--NORMAL--"

PROMPT='%{$fg[green]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%~ %{$fg[red]%}$(git_prompt_info) %{$fg[cyan]%}$(vi_mode_prompt_info) %{$reset_color%}
%{$reset_color%} α '
RPS1='ω'

# }}}

# {{{ aliases

# default flags and 'settings'
alias ls='ls --color -hF'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -al'
alias lsa='ls -a'
alias df='df -h'
alias less='less -r'
alias lessf='less -n +F' # Works like tail
alias lessg='less +G' # Go to bottom

# oops
alias sl='ls'
alias dc='cd'
alias cd..='cd ..'

# if I'm stuck in vim mode
alias :q='exit'

# aliases pertaining to completion
alias man='nocorrect man'
alias mv='nocorrect mv'

# tmux
alias tmux='tmux -2'
alias ta='tmux attach-session -t'
alias tl='tmux list-sessions'
alias tc='tmux new-session -s'

# whe? wha? who?
alias whe='whereis'
alias wha='whatis'

# always colors in grep unless I say so
alias grep='grep --colour=always'

# global aliases, can be used anywhere in a line
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias -g L="| less"
alias -g G="| grep"
alias -g H="| head"
alias -g T="| tail"

# }}}

# {{{ virtualenvwrapper

export WORKON_HOME=~/.virtualenvs
# Ubuntu
if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi
# Fedora
if [[ -r /usr/bin/virtualenvwrapper.sh ]]; then
  source /usr/bin/virtualenvwrapper.sh
fi

# }}}

# {{{ exports

case "$TERM" in
       xterm*) export TERM=xterm-256color
esac

export EDITOR='vim'

# add bin folder in home to path
export PATH=$PATH:$HOME/.bin

# set up the cd path
if [[ -r $HOME/projects ]]; then
  export CDPATH=$CDPATH:$HOME/projects
fi

# Ruby Environment thingamijigger
if [[ -r $HOME/.rbenv ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
  export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
fi

# Only add heroku to path if heroku path exists
if [[ -r /usr/local/heroku ]]; then
  ### Added by the Heroku Toolbelt
  export PATH="/usr/local/heroku/bin:$PATH"
fi

# }}}

# {{{ Local machine settings

if [[ -r $HOME/.localzshrc ]]; then
  source $HOME/.localzshrc
fi

# }}}
